package com.arn.scrobble.info

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.arn.scrobble.api.Requesters
import com.arn.scrobble.api.lastfm.Track
import com.arn.scrobble.db.PanoDb
import com.arn.scrobble.utils.PlatformStuff
import com.arn.scrobble.utils.YouTubeMusicPlaylistResult
import kotlinx.coroutines.flow.MutableSharedFlow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.asSharedFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.launch

private const val playlistFetchLimit = 90
private const val playlistMaxTracks = 25

class SimilarTracksPlaylistVM(
    private val seedTrack: Track,
) : ViewModel() {
    private val _isCreatingPlaylist = MutableStateFlow(false)
    val isCreatingPlaylist = _isCreatingPlaylist.asStateFlow()

    private val _playlistCreationResult =
        MutableSharedFlow<Result<YouTubeMusicPlaylistResult>>(extraBufferCapacity = 1)
    val playlistCreationResult = _playlistCreationResult.asSharedFlow()

    fun createPlaylist(authFileUri: String?) {
        if (_isCreatingPlaylist.value) {
            return
        }

        viewModelScope.launch {
            _isCreatingPlaylist.emit(true)
            val result = runCatching {
                require(PlatformStuff.isDesktop) {
                    "YouTube Music playlist creation with ytmusicapi is only available on desktop."
                }
                require(!authFileUri.isNullOrBlank()) {
                    "Select a YouTube Music auth JSON file first."
                }

                val lastIndexedAt = PlatformStuff.mainPrefs.data.map { it.lastMaxIndexTime }.first()
                require(lastIndexedAt != null) {
                    "Index your scrobbles first so recommended tracks can be filtered to unheard songs."
                }

                val unheardTracks = loadUnheardRecommendedTracks()
                require(unheardTracks.isNotEmpty()) {
                    "No unheard recommended tracks were found for this song."
                }

                PlatformStuff.createYouTubeMusicPlaylist(
                    playlistName = buildPlaylistName(),
                    description = buildPlaylistDescription(unheardTracks.size),
                    authFileUri = authFileUri,
                    tracks = unheardTracks,
                ).getOrThrow()
            }
            _playlistCreationResult.emit(result)
            _isCreatingPlaylist.emit(false)
        }
    }

    private suspend fun loadUnheardRecommendedTracks(): List<Track> {
        val dao = PanoDb.db.getCachedTracksDao()
        return Requesters.lastfmUnauthedRequester.trackGetSimilar(
            seedTrack,
            limit = playlistFetchLimit,
        ).getOrThrow()
            .filter { it.artist.name.isNotBlank() && it.name.isNotBlank() }
            .filterNot {
                it.artist.name.equals(seedTrack.artist.name, ignoreCase = true) &&
                        it.name.equals(seedTrack.name, ignoreCase = true)
            }
            .distinctBy { it.artist.name.lowercase() + "\u0000" + it.name.lowercase() }
            .filter { recommendedTrack ->
                val cachedTrack = dao.findExact(recommendedTrack.artist.name, recommendedTrack.name)
                (cachedTrack?.plays ?: 0) <= 0
            }
            .take(playlistMaxTracks)
    }

    private fun buildPlaylistName(): String {
        return "Unheard recommendations from ${seedTrack.artist.name} - ${seedTrack.name}"
    }

    private fun buildPlaylistDescription(trackCount: Int): String {
        return buildString {
            append("Generated by Pano Scrobbler from similar tracks to ")
            append(seedTrack.artist.name)
            append(" - ")
            append(seedTrack.name)
            append(". ")
            append(trackCount)
            append(" unheard recommendation")
            if (trackCount != 1) append('s')
            append(" added.")
        }
    }
}

